package com.campusconnect.controller;
import com.campusconnect.model.Complaint; import com.campusconnect.service.ComplaintService; import com.campusconnect.util.SessionManager; import javafx.collections.*; import javafx.fxml.FXML; import javafx.scene.control.*; import javafx.scene.control.cell.PropertyValueFactory; import java.util.*;
public class ComplaintController { @FXML private TableView<Complaint> table; @FXML private Button backButton; private final ComplaintService service=new ComplaintService();
 @FXML private void initialize(){for(String x:new String[]{"id","studentName","category","description","priority","status","resolutionRemarks","createdAt"}){TableColumn<Complaint,Object> c=new TableColumn<>(x.equals("studentName")?"Student":x.substring(0,1).toUpperCase()+x.substring(1));c.setCellValueFactory(new PropertyValueFactory<>(x));c.setPrefWidth(x.equals("description")?240:120);table.getColumns().add(c);}refresh();}
 private void refresh(){try{table.setItems(FXCollections.observableArrayList(SessionManager.isAdmin()?service.all():service.forStudent(SessionManager.getUser().getId())));}catch(Exception e){UiUtil.error(e.getMessage());}}
 @FXML private void create(){if(SessionManager.isAdmin())return;try{Complaint c=new Complaint();c.setStudentId(SessionManager.getUser().getId());c.setCategory(choice("Category",new String[]{"Electrical","Plumbing","Internet","Cleaning","Furniture","Other"}));c.setDescription(input("Description","").orElseThrow());c.setPriority(choice("Priority",new String[]{"Low","Medium","High","Critical"}));service.create(c);refresh();}catch(Exception e){UiUtil.error(e.getMessage());}}
 @FXML private void update(){if(!SessionManager.isAdmin()){create();return;}Complaint c=table.getSelectionModel().getSelectedItem();if(c==null)return;try{String st=choice("Status",new String[]{"Pending","In Progress","Resolved","Rejected"});String pr=choice("Priority",new String[]{"Low","Medium","High","Critical"});String rem=input("Resolution remarks",c.getResolutionRemarks()).orElse("");service.update(c.getId(),st,pr,rem);refresh();}catch(Exception e){UiUtil.error(e.getMessage());}}
 @FXML private void delete(){Complaint c=table.getSelectionModel().getSelectedItem();if(c!=null&&SessionManager.isAdmin()&&UiUtil.confirm("Delete this complaint?")){service.delete(c.getId());refresh();}}
 private Optional<String> input(String h,String def){TextInputDialog d=new TextInputDialog(def);d.setTitle("Complaint");d.setHeaderText(h);d.setContentText(h+":");return d.showAndWait();} private String choice(String h,String[] vals){ChoiceDialog<String>d=new ChoiceDialog<>(vals[0],vals);d.setTitle("Complaint");d.setHeaderText(h);return d.showAndWait().orElseThrow();}
 @FXML private void back(){UiUtil.scene(backButton,SessionManager.isAdmin()?"admin-dashboard.fxml":"student-dashboard.fxml");}
}
