package com.campusconnect.controller;
import com.campusconnect.model.*; import com.campusconnect.service.EventService; import com.campusconnect.util.SessionManager; import javafx.collections.*; import javafx.fxml.FXML; import javafx.scene.control.*; import javafx.scene.control.cell.PropertyValueFactory; import java.time.*; import java.util.*;
public class EventController { @FXML private TableView<Event> table; @FXML private Button backButton; private final EventService service=new EventService();
 @FXML private void initialize(){for(String x:new String[]{"id","name","description","venue","date","time","capacity","registeredCount","organizer"}){TableColumn<Event,Object> c=new TableColumn<>(x.equals("registeredCount")?"Registered":x.substring(0,1).toUpperCase()+x.substring(1));c.setCellValueFactory(new PropertyValueFactory<>(x));c.setPrefWidth(x.equals("description")?220:110);table.getColumns().add(c);}refresh();}
 private void refresh(){try{table.setItems(FXCollections.observableArrayList(service.all()));}catch(Exception e){UiUtil.error(e.getMessage());}}
 @FXML private void create(){if(!SessionManager.isAdmin())return;try{Event e=form(null);service.save(e,false);refresh();}catch(Exception ex){UiUtil.error(ex.getMessage());}}
 @FXML private void edit(){if(!SessionManager.isAdmin())return;Event old=table.getSelectionModel().getSelectedItem();if(old==null)return;try{service.save(form(old),true);refresh();}catch(Exception e){UiUtil.error(e.getMessage());}}
 @FXML private void viewRegistrations(){if(!SessionManager.isAdmin())return;Event e=table.getSelectionModel().getSelectedItem();if(e==null)return;try{var list=service.eventRegistrations(e.getId());StringBuilder b=new StringBuilder("Registrations for "+e.getName()+"\n\n");for(var r:list)b.append(r.getStudentName()).append(" • ").append(r.getRegisteredAt()).append("\n");UiUtil.alert("Registered Students",b.toString());}catch(Exception x){UiUtil.error(x.getMessage());}}
 @FXML private void delete(){Event e=table.getSelectionModel().getSelectedItem();if(e!=null&&SessionManager.isAdmin()&&UiUtil.confirm("Delete this event?")){try{service.delete(e.getId());refresh();}catch(Exception x){UiUtil.error(x.getMessage());}}}
 @FXML private void register(){if(SessionManager.isAdmin())return;Event e=table.getSelectionModel().getSelectedItem();if(e==null)return;try{service.register(e.getId(),SessionManager.getUser().getId());UiUtil.alert("Registered","You are registered for "+e.getName()+".");refresh();}catch(Exception x){UiUtil.error(x.getMessage());}}
 @FXML private void cancel(){if(SessionManager.isAdmin())return;Event e=table.getSelectionModel().getSelectedItem();if(e==null)return;try{service.cancel(e.getId(),SessionManager.getUser().getId());refresh();}catch(Exception x){UiUtil.error(x.getMessage());}}
 private Event form(Event old){String name=input("Event name",old==null?"":old.getName()).orElseThrow();String desc=input("Description",old==null?"":old.getDescription()).orElseThrow();String venue=input("Venue",old==null?"":old.getVenue()).orElseThrow();String date=input("Date (YYYY-MM-DD)",old==null?LocalDate.now().toString():old.getDate().toString()).orElseThrow();String time=input("Time (HH:MM)",old==null?"10:00":old.getTime().toString()).orElseThrow();String cap=input("Capacity",old==null?"50":String.valueOf(old.getCapacity())).orElseThrow();String org=input("Organizer",old==null?"CampusConnect":old.getOrganizer()).orElseThrow();Event e=old==null?new Event():old;e.setName(name);e.setDescription(desc);e.setVenue(venue);e.setDate(LocalDate.parse(date));e.setTime(LocalTime.parse(time));e.setCapacity(Integer.parseInt(cap));e.setOrganizer(org);return e;}private Optional<String> input(String h,String d){TextInputDialog x=new TextInputDialog(d);x.setTitle("Event");x.setHeaderText(h);return x.showAndWait();} @FXML private void back(){UiUtil.scene(backButton,SessionManager.isAdmin()?"admin-dashboard.fxml":"student-dashboard.fxml");}
}
