package com.campusconnect.controller;
import com.campusconnect.model.*; import com.campusconnect.service.LostFoundService; import com.campusconnect.util.SessionManager; import javafx.collections.*; import javafx.fxml.FXML; import javafx.scene.control.*; import javafx.scene.control.cell.PropertyValueFactory; import java.time.LocalDate; import java.util.*;
public class LostFoundController { @FXML private TableView<LostFoundItem> table; @FXML private TextField searchField; @FXML private ComboBox<String> categoryBox; @FXML private Button backButton; private final LostFoundService service=new LostFoundService();
 @FXML private void initialize(){categoryBox.getItems().addAll("All","Electronics","Documents","Accessories","Books","Clothing","Other");categoryBox.setValue("All");for(String x:new String[]{"id","title","description","category","location","itemDate","status","posterName"}){TableColumn<LostFoundItem,Object> c=new TableColumn<>(x.equals("itemDate")?"Date":x.equals("posterName")?"Posted By":x.substring(0,1).toUpperCase()+x.substring(1));c.setCellValueFactory(new PropertyValueFactory<>(x));c.setPrefWidth(x.equals("description")?230:120);table.getColumns().add(c);}refresh();}
 private void refresh(){try{table.setItems(FXCollections.observableArrayList(service.all(searchField.getText(),categoryBox.getValue())));}catch(Exception e){UiUtil.error(e.getMessage());}} @FXML private void search(){refresh();}
 @FXML private void post(){try{LostFoundItem x=new LostFoundItem();x.setTitle(input("Title","").orElseThrow());x.setDescription(input("Description","").orElseThrow());x.setCategory(choice("Category",new String[]{"Electronics","Documents","Accessories","Books","Clothing","Other"}));x.setLocation(input("Location","").orElseThrow());x.setItemDate(LocalDate.now());x.setStatus(choice("Type",new String[]{"Lost","Found"}));x.setPostedBy(SessionManager.getUser().getId());service.create(x);refresh();}catch(Exception e){UiUtil.error(e.getMessage());}}
 @FXML private void claim(){LostFoundItem x=table.getSelectionModel().getSelectedItem();if(x==null||SessionManager.isAdmin()){UiUtil.error("Select an item to claim.");return;}try{service.claim(x.getId(),SessionManager.getUser().getId());UiUtil.alert("Claim submitted","Your claim request was submitted for admin verification.");}catch(Exception e){UiUtil.error(e.getMessage());}}
 @FXML private void manage(){LostFoundItem x=table.getSelectionModel().getSelectedItem();if(x==null||!SessionManager.isAdmin())return;try{String st=choice("Status",new String[]{"Lost","Found","Claimed","Returned"});service.itemStatus(x.getId(),st);refresh();}catch(Exception e){UiUtil.error(e.getMessage());}}
 @FXML private void claims(){if(!SessionManager.isAdmin())return;try{var list=service.claims(0);if(list.isEmpty()){UiUtil.alert("Claims","No claim requests.");return;}StringBuilder b=new StringBuilder();for(var c:list)b.append("#").append(c.getId()).append(" • ").append(c.getItemTitle()).append(" • ").append(c.getStudentName()).append(" • ").append(c.getStatus()).append("\n");TextInputDialog d=new TextInputDialog();d.setTitle("Claim Requests");d.setHeaderText(b.toString());d.setContentText("Enter claim ID to update:");d.showAndWait().ifPresent(v->{try{int id=Integer.parseInt(v);String st=choice("Claim status",new String[]{"Approved","Rejected","Pending"});service.claimStatus(id,st);UiUtil.alert("Claims","Claim updated.");}catch(Exception e){UiUtil.error(e.getMessage());}});}catch(Exception e){UiUtil.error(e.getMessage());}}
 @FXML private void delete(){LostFoundItem x=table.getSelectionModel().getSelectedItem();if(x!=null&&SessionManager.isAdmin()&&UiUtil.confirm("Delete this post?")){service.delete(x.getId());refresh();}}
 private Optional<String> input(String h,String d){TextInputDialog x=new TextInputDialog(d);x.setTitle("Lost & Found");x.setHeaderText(h);return x.showAndWait();}private String choice(String h,String[] a){ChoiceDialog<String>x=new ChoiceDialog<>(a[0],a);x.setTitle("Lost & Found");x.setHeaderText(h);return x.showAndWait().orElseThrow();} @FXML private void back(){UiUtil.scene(backButton,SessionManager.isAdmin()?"admin-dashboard.fxml":"student-dashboard.fxml");}
}
