package com.campusconnect.controller;
import com.campusconnect.model.Student; import com.campusconnect.service.StudentService; import com.campusconnect.util.SessionManager; import javafx.collections.*; import javafx.fxml.FXML; import javafx.scene.control.*; import javafx.scene.control.cell.PropertyValueFactory; import java.time.LocalDate; import java.util.*;
public class StudentController { @FXML private TableView<Student> table; @FXML private TextField searchField; @FXML private Button backButton,addButton; private final StudentService service=new StudentService();
 @FXML private void initialize(){String[] n={"studentId","name","email","phone","department","semester","hostelRoom","registrationDate"};for(String x:n){TableColumn<Student,Object> c=new TableColumn<>(switch(x){case"studentId"->"Student ID";case"hostelRoom"->"Hostel/Room";case"registrationDate"->"Registered";default->Character.toUpperCase(x.charAt(0))+x.substring(1);});c.setCellValueFactory(new PropertyValueFactory<>(x));c.setPrefWidth(125);table.getColumns().add(c);}refresh();}
 private void refresh(){try{table.setItems(FXCollections.observableArrayList(service.all(searchField.getText())));}catch(Exception e){UiUtil.error(e.getMessage());}}
 @FXML private void search(){refresh();} @FXML private void add(){try{Student s=form(null);service.save(s,false);refresh();UiUtil.alert("Student added","Student account created successfully.");}catch(Exception e){UiUtil.error(e.getMessage());}} @FXML private void edit(){Student s=table.getSelectionModel().getSelectedItem();if(s==null){UiUtil.error("Select a student first.");return;}try{Student x=form(s);service.save(x,true);refresh();}catch(Exception e){UiUtil.error(e.getMessage());}}
 @FXML private void delete(){Student s=table.getSelectionModel().getSelectedItem();if(s==null)return;if(UiUtil.confirm("Delete "+s.getName()+" and their account?")){try{service.delete(s.getId());refresh();}catch(Exception e){UiUtil.error(e.getMessage());}}}
 private Student form(Student old){List<String> v=new ArrayList<>();String[] labels={"Student ID","Name","Email","Phone","Department","Semester","Hostel/Room"};for(String l:labels){TextInputDialog d=new TextInputDialog();d.setTitle(old==null?"Add Student":"Edit Student");d.setHeaderText(l);d.setContentText(l+":");String def=old==null?"":switch(l){case"Student ID"->old.getStudentId();case"Name"->old.getName();case"Email"->old.getEmail();case"Phone"->old.getPhone();case"Department"->old.getDepartment();case"Semester"->String.valueOf(old.getSemester());default->old.getHostelRoom();};d.getEditor().setText(def);Optional<String> r=d.showAndWait();if(r.isEmpty())throw new IllegalArgumentException("Operation cancelled.");v.add(r.get());}Student s=old==null?new Student():old;s.setStudentId(v.get(0));s.setName(v.get(1));s.setEmail(v.get(2));s.setPhone(v.get(3));s.setDepartment(v.get(4));s.setSemester(Integer.parseInt(v.get(5)));s.setHostelRoom(v.get(6));s.setRegistrationDate(LocalDate.now());if(old==null){TextInputDialog d=new TextInputDialog();d.setTitle("Password");d.setHeaderText("Initial password");d.setContentText("Password:");Optional<String> r=d.showAndWait();if(r.isEmpty())throw new IllegalArgumentException("Operation cancelled.");s.setPasswordHash(r.get());}return s;}
 @FXML private void back(){UiUtil.scene(backButton,SessionManager.isAdmin()?"admin-dashboard.fxml":"student-dashboard.fxml");}
}
