package com.campusconnect.dao;
import com.campusconnect.exception.DatabaseException; import com.campusconnect.model.*; import com.campusconnect.util.DatabaseConnection; import java.sql.*; import java.util.*;
public class EventDAO { private Event map(ResultSet r)throws SQLException{Event e=new Event();e.setId(r.getInt("id"));e.setName(r.getString("name"));e.setDescription(r.getString("description"));e.setVenue(r.getString("venue"));e.setDate(r.getDate("event_date").toLocalDate());e.setTime(r.getTime("event_time").toLocalTime());e.setCapacity(r.getInt("capacity"));e.setOrganizer(r.getString("organizer"));e.setRegisteredCount(r.getInt("registered_count"));return e;}
 public List<Event> findUpcoming(){return query("WHERE e.event_date>=CURRENT_DATE");} public List<Event> findAll(){return query("");} private List<Event> query(String w){List<Event>a=new ArrayList<>();String sql="SELECT e.*,COUNT(r.id) registered_count FROM events e LEFT JOIN event_registrations r ON r.event_id=e.id "+w+" GROUP BY e.id ORDER BY e.event_date,e.event_time";try(Connection c=DatabaseConnection.getConnection();PreparedStatement p=c.prepareStatement(sql);ResultSet r=p.executeQuery()){while(r.next())a.add(map(r));}catch(SQLException e){throw new DatabaseException("Could not load events.",e);}return a;}
 public void insert(Event e){String sql="INSERT INTO events(name,description,venue,event_date,event_time,capacity,organizer) VALUES(?,?,?,?,?,?,?)";write(sql,e,0);} public void update(Event e){String sql="UPDATE events SET name=?,description=?,venue=?,event_date=?,event_time=?,capacity=?,organizer=? WHERE id=?";write(sql,e,e.getId());} private void write(String sql,Event e,int id){try(Connection c=DatabaseConnection.getConnection();PreparedStatement p=c.prepareStatement(sql)){p.setString(1,e.getName());p.setString(2,e.getDescription());p.setString(3,e.getVenue());p.setDate(4,Date.valueOf(e.getDate()));p.setTime(5,Time.valueOf(e.getTime()));p.setInt(6,e.getCapacity());p.setString(7,e.getOrganizer());if(id>0)p.setInt(8,id);p.executeUpdate();}catch(SQLException x){throw new DatabaseException("Could not save event.",x);}}
 public void delete(int id){try(Connection c=DatabaseConnection.getConnection();PreparedStatement p=c.prepareStatement("DELETE FROM events WHERE id=?")){p.setInt(1,id);p.executeUpdate();}catch(SQLException e){throw new DatabaseException("Could not delete event.",e);}}
 public int registrations(){try(Connection c=DatabaseConnection.getConnection();Statement s=c.createStatement();ResultSet r=s.executeQuery("SELECT COUNT(*) FROM event_registrations")){r.next();return r.getInt(1);}catch(SQLException e){throw new DatabaseException("Could not read registration statistics.",e);}}
 public void register(int eventId,int studentId){String cap="SELECT capacity,(SELECT COUNT(*) FROM event_registrations WHERE event_id=e.id) cnt FROM events e WHERE id=?";try(Connection c=DatabaseConnection.getConnection()){c.setAutoCommit(false);try{try(PreparedStatement p=c.prepareStatement(cap)){p.setInt(1,eventId);try(ResultSet r=p.executeQuery()){if(!r.next())throw new IllegalArgumentException("Event not found.");if(!com.campusconnect.util.EventCapacityUtil.canRegister(r.getInt("capacity"),r.getInt("cnt")))throw new IllegalStateException("Event capacity is full.");}}try(PreparedStatement p=c.prepareStatement("INSERT INTO event_registrations(event_id,student_id) VALUES(?,?)")){p.setInt(1,eventId);p.setInt(2,studentId);p.executeUpdate();}c.commit();}catch(Exception e){c.rollback();throw e;}}catch(SQLException e){throw new DatabaseException("Could not register for event.",e);}}
 public void cancel(int eventId,int studentId){try(Connection c=DatabaseConnection.getConnection();PreparedStatement p=c.prepareStatement("DELETE FROM event_registrations WHERE event_id=? AND student_id=?")){p.setInt(1,eventId);p.setInt(2,studentId);p.executeUpdate();}catch(SQLException e){throw new DatabaseException("Could not cancel registration.",e);}}
 public List<EventRegistration> registrationsForStudent(int sid){return registrationsQuery("WHERE r.student_id=?",sid);} public List<EventRegistration> registrationsForEvent(int eid){return registrationsQuery("WHERE r.event_id=?",eid);} private List<EventRegistration> registrationsQuery(String w,int id){List<EventRegistration>a=new ArrayList<>();String sql="SELECT r.id,r.event_id,r.student_id,e.name event_name,s.name student_name,r.registered_at FROM event_registrations r JOIN events e ON e.id=r.event_id JOIN students s ON s.user_id=r.student_id "+w+" ORDER BY r.registered_at DESC";try(Connection c=DatabaseConnection.getConnection();PreparedStatement p=c.prepareStatement(sql)){p.setInt(1,id);try(ResultSet r=p.executeQuery()){while(r.next()){EventRegistration x=new EventRegistration();x.setId(r.getInt(1));x.setEventId(r.getInt(2));x.setStudentId(r.getInt(3));x.setEventName(r.getString(4));x.setStudentName(r.getString(5));x.setRegisteredAt(r.getTimestamp(6).toLocalDateTime());a.add(x);}}}catch(SQLException e){throw new DatabaseException("Could not load registrations.",e);}return a;}
}
