package com.campusconnect.dao;
import com.campusconnect.exception.DatabaseException; import com.campusconnect.model.Student; import com.campusconnect.util.DatabaseConnection; import java.sql.*; import java.time.LocalDate; import java.util.*;
public class StudentDAO {
 private static final String BASE="SELECT u.id,u.email,u.password_hash,u.role,s.student_id,s.name,s.phone,s.department,s.semester,s.hostel_room,s.registration_date FROM students s JOIN users u ON u.id=s.user_id ";
 private Student map(ResultSet r)throws SQLException{return new Student(r.getInt(1),r.getString(2),r.getString(3),r.getString(4),r.getString(5),r.getString(6),r.getString(7),r.getString(8),r.getInt(9),r.getString(10),r.getDate(11).toLocalDate());}
 public List<Student> findAll(String q){List<Student> out=new ArrayList<>();String sql=BASE+"WHERE s.student_id LIKE ? OR s.name LIKE ? OR s.email LIKE ? ORDER BY s.name";try(Connection c=DatabaseConnection.getConnection();PreparedStatement p=c.prepareStatement(sql)){String x="%"+(q==null?"":q.trim())+"%";p.setString(1,x);p.setString(2,x);p.setString(3,x);try(ResultSet r=p.executeQuery()){while(r.next())out.add(map(r));}}catch(SQLException e){throw new DatabaseException("Could not load students.",e);}return out;}
 public Student findByUserId(int id){try(Connection c=DatabaseConnection.getConnection();PreparedStatement p=c.prepareStatement(BASE+"WHERE u.id=?")){p.setInt(1,id);try(ResultSet r=p.executeQuery()){return r.next()?map(r):null;}}catch(SQLException e){throw new DatabaseException("Could not load student.",e);}}
 public int count(){return scalar("SELECT COUNT(*) FROM students");}
 private int scalar(String sql){try(Connection c=DatabaseConnection.getConnection();Statement s=c.createStatement();ResultSet r=s.executeQuery(sql)){r.next();return r.getInt(1);}catch(SQLException e){throw new DatabaseException("Could not read statistics.",e);}}
 public void insert(Student s){String u="INSERT INTO users(email,password_hash,role) VALUES(?,?, 'STUDENT')";String st="INSERT INTO students(user_id,student_id,name,phone,department,semester,hostel_room,registration_date) VALUES(?,?,?,?,?,?,?,?)";try(Connection c=DatabaseConnection.getConnection()){c.setAutoCommit(false);try(PreparedStatement a=c.prepareStatement(u,Statement.RETURN_GENERATED_KEYS);PreparedStatement b=c.prepareStatement(st)){a.setString(1,s.getEmail());a.setString(2,s.getPasswordHash());a.executeUpdate();try(ResultSet k=a.getGeneratedKeys()){k.next();int id=k.getInt(1);b.setInt(1,id);b.setString(2,s.getStudentId());b.setString(3,s.getName());b.setString(4,s.getPhone());b.setString(5,s.getDepartment());b.setInt(6,s.getSemester());b.setString(7,s.getHostelRoom());b.setDate(8,Date.valueOf(s.getRegistrationDate()==null?LocalDate.now():s.getRegistrationDate()));b.executeUpdate();c.commit();}}catch(SQLException e){c.rollback();throw e;}}catch(SQLException e){throw new DatabaseException("Could not add student. Check duplicate ID/email.",e);}}
 public void update(Student s){String sql="UPDATE students s JOIN users u ON u.id=s.user_id SET u.email=?,s.student_id=?,s.name=?,s.phone=?,s.department=?,s.semester=?,s.hostel_room=? WHERE s.user_id=?";try(Connection c=DatabaseConnection.getConnection();PreparedStatement p=c.prepareStatement(sql)){p.setString(1,s.getEmail());p.setString(2,s.getStudentId());p.setString(3,s.getName());p.setString(4,s.getPhone());p.setString(5,s.getDepartment());p.setInt(6,s.getSemester());p.setString(7,s.getHostelRoom());p.setInt(8,s.getId());p.executeUpdate();}catch(SQLException e){throw new DatabaseException("Could not update student.",e);}}
 public void delete(int id){try(Connection c=DatabaseConnection.getConnection();PreparedStatement p=c.prepareStatement("DELETE FROM users WHERE id=?")){p.setInt(1,id);p.executeUpdate();}catch(SQLException e){throw new DatabaseException("Could not delete student.",e);}}
}
